Repository CheckMate-sookmyung/CheckMate-client, pull requests merged in 2024-08, with the labels that each got.

#192 fix: 행사 등록 페이지 통합
  src/pages/DashboardPage/DashboardInfoPage.jsx
  src/pages/RegisterPage/PageComponents/RegisterFirst.jsx
  src/pages/RegisterPage/PageComponents/RegisterSecond.jsx
  src/pages/RegisterPage/PageComponents/RegisterThird.jsx
  src/pages/RegisterPage/RegisterComponents/RegisterSecond.jsx
  src/pages/RegisterPage/RegisterComponents/UploadBox.jsx
  src/pages/RegisterPage/RegisterPage.jsx
  src/pages/RegisterPage/RegisterStyle.js
Labels: 🔧 fix

#193 fix: 행사 등록 과정 수정
  src/pages/RegisterPage/PageComponents/RegisterSecond.jsx
  src/pages/RegisterPage/PageComponents/RegisterThird.jsx
  src/pages/RegisterPage/RegisterComponents/Scheduler.jsx
  src/pages/RegisterPage/RegisterStyle.js
Labels: 🐞 bug fix, 🎨 UI

#194 merge: dev to main
  src/pages/DashboardPage/DashboardInfoPage.jsx
  src/pages/RegisterPage/PageComponents/RegisterFirst.jsx
  src/pages/RegisterPage/PageComponents/RegisterSecond.jsx
  src/pages/RegisterPage/RegisterComponents/RegisterSecond.jsx
  src/pages/RegisterPage/RegisterComponents/RegisterThird.jsx
  src/pages/RegisterPage/RegisterComponents/Scheduler.jsx
  src/pages/RegisterPage/RegisterComponents/UploadBox.jsx
  src/pages/RegisterPage/RegisterPage.jsx
  src/pages/RegisterPage/RegisterStyle.js
Labels: 🌏 deploy

#195 modify: 참석자 명단 리스트에서 표제목 일부 변경
  src/pages/DashboardPage/DashboardAttendeePage.jsx
Labels: 🎨 UI

#196 merge: dev to main
  src/pages/DashboardPage/DashboardAttendeePage.jsx
  src/pages/RegisterPage/PageComponents/RegisterSecond.jsx
Labels: 🌏 deploy

#198 #197 feat: 버튼 컴포넌트 생성 및 대시보드 페이지에 일부 적용
  src/components/Button/BlueButton/BlueButton.jsx
  src/components/Button/BlueButton/BlueButtonStyle.jsx
  src/components/Button/GrayButton/GrayButton.jsx
  src/components/Button/GrayButton/GrayButtonStyle.jsx
  src/components/Button/index.js
  src/pages/DashboardPage/DashboardPage.jsx
Labels: 💫 feature

#201 #199 modify: 대시보드 페이지 일부 수정
  src/pages/DashboardPage/DashboardPage.jsx
  src/pages/DashboardPage/DashboardPage.style.jsx
Labels: 🎨 UI

#204 #197 modify: 버튼 컴포넌트 수정 및 적용
  src/components/Button/BlueButton/BlueButton.jsx
  src/components/Button/BlueButton90.jsx
  src/components/Button/Button.jsx
  src/components/Button/ButtonStyle.jsx
  src/components/Button/GrayButton/GrayButton.jsx
  src/components/Button/GrayButton/GrayButtonStyle.jsx
  src/components/Button/GrayButton90.jsx
  src/components/Button/TabButton90.jsx
  src/components/Button/index.js
  src/components/index.js
  src/pages/DashboardPage/DashboardAttendeePage.jsx
  src/pages/DashboardPage/DashboardEmailPage.jsx
  src/pages/DashboardPage/DashboardInfoPage.jsx
  src/pages/DashboardPage/DashboardPage.jsx
  src/pages/Home/Home.Style.js
  src/pages/Home/Home.jsx
Labels: 🎨 UI

#206 #205 feat: 헤더에 로고 추가, craco 패키지 설치
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
  .github/pull_request_template.md
  craco.config.js
  jsconfig.json
  package-lock.json
  package.json
  src/Layout/Layout.jsx
  src/components/AttendanceConfirmModal/index.js
  src/components/EventCard/EventCard.jsx
  src/components/EventCard/EventCard.style.jsx
  src/components/EventCard/index.js
  src/components/Navigator/Navigator.jsx
  src/components/Navigator/Navigator.style.jsx
  src/components/Navigator/Sidebar.jsx
  src/components/index.js
  src/pages/AttendancePage/AttendanceSignPage.jsx
  src/pages/AttendancePage/AttendanceStudentIdPage.jsx
  src/pages/DashboardPage/DashboardAttendeePage.jsx
  src/pages/DashboardPage/DashboardEmailPage.jsx
  src/pages/DashboardPage/DashboardInfoPage.jsx
  src/pages/DashboardPage/DashboardPage.jsx
  src/pages/EventDetail/AttendanceList.jsx
  src/pages/EventDetail/EventDetailPage.jsx
  src/pages/EventDetail/EventDetailPage.style.jsx
  src/pages/EventDetail/index.js
  src/pages/EventList/index.js
  src/pages/EventListPage/EventListPage.jsx
  src/pages/EventListPage/EventListPage.style.jsx
  src/pages/EventListPage/index.js
  src/pages/Home/Home.Style.js
  src/pages/Home/Home.jsx
  src/pages/Home/index.js
  src/pages/RegisterPage/index.js
  src/pages/index.js
  src/router.js
Labels: 💫 feature

#207 #205 modify: 헤더메뉴 수정 및 통계페이지 생성
  src/components/Navigator/Navigator.jsx
  src/pages/TotalStatisticsPage/TotalStatisticsPage.jsx
  src/pages/TotalStatisticsPage/TotalStatisticsPage.style.jsx
  src/pages/TotalStatisticsPage/index.js
  src/pages/index.js
  src/router.js
Labels: 🎨 UI

#209 #208 style: 행사 목록 페이지 수정 및 토글, 행사 카드 컴포넌트 생성
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/Dropdown.style.jsx
  src/components/Dropdown/index.js
  src/components/EventCard/EventCard.jsx
  src/components/EventCard/EventCard.style.jsx
  src/components/index.js
  src/pages/EventCardListPage/EventCardListPage.jsx
  src/pages/EventCardListPage/EventCardListPage.style.jsx
  src/pages/EventCardListPage/index.js
  src/pages/EventListPage/index.js
  src/pages/index.js
  src/router.js
Labels: 💫 feature

#210 #208 style: 버튼 및 카드 테두리 스타일 수정
  src/components/EventCard/EventCard.style.jsx
Labels: 💫 feature

#212 #211 style: 페이지 max-width 1100px로 지정 및 홈화면 수정
  public/img/Bar.svg
  public/img/character-check.svg
  public/img/onboarding-diagram1.svg
  public/img/onboarding-diagram2.svg
  src/Layout/Layout.jsx
  src/components/Footer/Footer.Style.js
  src/components/Footer/Footer.jsx
  src/components/Navigator/index.js
  src/components/Sidebar/Sidebar.jsx
  src/components/Sidebar/Sidebar.style.jsx
  src/components/Sidebar/index.js
  src/components/TopNavigation/TopNavigation.jsx
  src/components/TopNavigation/TopNavigation.style.jsx
  src/components/TopNavigation/index.js
  src/components/index.js
  src/pages/EventCardListPage/EventCardListPage.jsx
  src/pages/EventCardListPage/EventCardListPage.style.jsx
  src/pages/Home/Home.Style.js
  src/pages/Home/Home.jsx
  src/pages/TotalStatisticsPage/TotalStatisticsPage.jsx
  src/pages/TotalStatisticsPage/TotalStatisticsPage.style.jsx
Labels: 💫 feature, 🎨 UI

#214 #199 design: 대시보드 페이지 이전 스타일 적용 및 디테일 수정
  src/components/Sidebar/Sidebar.jsx
  src/pages/DashboardPage/DashboardEmailPage.jsx
  src/pages/DashboardPage/DashboardEmailPage.style.jsx
  src/pages/DashboardPage/DashboardInfoPage.jsx
  src/pages/DashboardPage/DashboardInfoPage.style.jsx
  src/pages/DashboardPage/DashboardPage.jsx
  src/pages/DashboardPage/DashboardPage.style.jsx
Labels: 🎨 UI

#216 #215 design: `Top Navigation` 내 max-width 해제
  src/components/TopNavigation/TopNavigation.jsx
  src/components/TopNavigation/TopNavigation.style.jsx
Labels: 🎨 UI

#218 #127 refactor: component 분리 및 적용
  public/img/HomeBackground.png
  public/img/onboarding-1.png
  public/img/onboarding-2.png
  public/img/onboarding-3.png
  public/img/onboarding-4.png
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/Dropdown.style.jsx
  src/components/EventTargetOption/EventTargetOption.jsx
  src/components/EventTargetOption/EventTargetOption.style.jsx
  src/components/EventTargetOption/index.js
  src/components/Input/Input.jsx
  src/components/Input/Input.style.jsx
  src/components/Input/index.js
  src/components/Textarea/Textarea.jsx
  src/components/Textarea/Textarea.style.jsx
  src/components/Textarea/index.js
  src/components/index.js
  src/pages/DashboardPage/DashboardAttendeePage.jsx
  src/pages/DashboardPage/DashboardInfoPage.jsx
  src/pages/DashboardPage/DashboardInfoPage.style.jsx
  src/pages/DashboardPage/DashboardPage.style.jsx
  src/pages/EventCardListPage/EventCardListPage.jsx
  src/pages/Home/Home.jsx
Labels: ♻️ refactor

#220 #202 modify: 행사 등록 페이지 컴포넌트 및 디자인 수정
  src/components/ScrolltoTop/ScrolltoTop.jsx
  src/index.jsx
  src/pages/RegisterPage/PageComponents/RegisterCompleted.style.js
  src/pages/RegisterPage/PageComponents/RegisterFirst.jsx
  src/pages/RegisterPage/PageComponents/RegisterSecond.jsx
  src/pages/RegisterPage/RegisterComponents/EventTypeCard/EventTypeCard.jsx
  src/pages/RegisterPage/RegisterComponents/Scheduler/Scheduler.jsx
  src/pages/RegisterPage/RegisterComponents/Scheduler/Scheduler.style.js
  src/pages/RegisterPage/RegisterPage.jsx
Labels: 🎨 UI, 🔧 fix

#221 #127 refactor: 참석자 테이블 분리 등 디테일 수정
  src/components/Button/Button.jsx
  src/components/Button/Button.style.jsx
  src/components/EventCard/EventCard.style.jsx
  src/components/Sidebar/Sidebar.jsx
  src/components/Table/AttendeeTable.jsx
  src/components/Table/Table.style.jsx
  src/components/Table/TotalStatisticsTable.jsx
  src/components/Table/index.js
  src/components/TopNavigation/TopNavigation.jsx
  src/components/index.js
  src/pages/DashboardPage/DashboardAttendeePage.jsx
  src/pages/DashboardPage/DashboardAttendeePage.style.jsx
  src/pages/DashboardPage/DashboardPage.jsx
  src/pages/DashboardPage/DashboardPage.style.jsx
  src/pages/EventCardListPage/EventCardListPage.style.jsx
  src/styles/CheckMateStyles.style.jsx
Labels: ♻️ refactor
