Repository CheckMate-sookmyung/CheckMate-client, pull requests merged in 2024-06, with the labels that each got.

#86 Fix/attendance
  src/constants/tempData.js
  src/pages/EventDetail/AttendanceList.jsx
  src/pages/EventDetail/eventDetail.jsx
Labels: UI, fix

#89 포스터 위치 명단 대체, 날짜 캘린더, 백그라운드 수정
  src/components/Calendar/DateCalendar.jsx
  src/components/Calendar/DateCalendarStyle.js
  src/pages/EventDetail/AttendanceList.jsx
  src/pages/EventDetail/eventDetail.jsx
  src/pages/registerPage/register.jsx
Labels: feature, UI, fix

#90 modify: #87 서명 페이지 모바일 반응형 구현 완료
  src/components/AttendanceHeader/AttendanceHeader.style.jsx
  src/pages/AttendanceSignPage/AttendanceSignPage.jsx
  src/pages/AttendanceSignPage/AttendanceSignPage.style.jsx
  src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.style.jsx
Labels: modify

#94 Fix/register
  package.json
  src/components/Calendar/DateCalendar.jsx
  src/components/Calendar/DateCalendarStyle.js
  src/components/Calendar/TimeCalendar.jsx
  src/pages/registerPage/register.jsx
  src/styles/CheckMateStyles.style.jsx
Labels: feature, fix

#95 Fix/current event
  src/components/Background/BackgroundPage.jsx
  src/components/navigator.jsx
  src/pages/EventList/currentEvent.jsx
  src/pages/registerPage/register.jsx
Labels: UI, fix

#99 feat: 상태관리 추가
  package.json
  src/components/Calendar/DateCalendar.jsx
  src/index.jsx
  src/pages/EventDetail/AttendanceList.jsx
  src/pages/EventDetail/eventDetail.jsx
  src/pages/EventList/currentEvent.jsx
  src/recoil/atoms/state.js
Labels: feature, API

#101 modify: #87 행사 등록페이지 반응형 구현
  public/index.html
  src/components/Background/BackgroundPage.jsx
  src/components/Calendar/DateCalendar.jsx
  src/components/Calendar/TimeCalendar.jsx
  src/components/navigator.jsx
  src/pages/EventDetail/AttendanceList.jsx
  src/pages/EventDetail/eventDetail.jsx
  src/pages/EventList/currentEvent.jsx
  src/pages/registerPage/register.jsx
Labels: UI
