Repository CheckMate-sookmyung/CheckMate-client, pull requests merged in 2024-07, with the labels that each got.

#104 feat: #102 행사 삭제 기능 구현
  src/constants/tempData.js
  src/pages/EventDetail/AttendanceList.jsx
  src/pages/EventDetail/EventDetailPage.jsx
  src/pages/EventDetail/EventDetailPage.style.jsx
  src/pages/EventDetail/eventDetail.jsx
  src/pages/EventDetail/index.js
  src/router.js
  src/styles/mediaQueries.style.js
Labels: feature, UI, API

#106 Fix: 캘린더 수정사항
  src/components/Calendar/DateCalendar.jsx
  src/components/Calendar/DateCalendarStyle.js
  src/components/Calendar/TimeCalendar.jsx
  src/components/Calendar/TimeCalendarStyle.js
Labels: UI, fix

#112 Feat: 홈화면 구현
  src/pages/Home/Home.jsx
  src/pages/Home/HomeCarousel/HomeCarousel.js
  src/pages/Home/HomeCarousel/HomeCarousel.jsx
  src/pages/Home/HomeStyle.js
  src/router.js
Labels: feature

#114 feat: #113 대시보드 페이지 view 구현
  src/pages/DashboardPage/DashboardPage.jsx
  src/pages/DashboardPage/DashboardPage.style.jsx
  src/pages/DashboardPage/index.js
  src/pages/index.js
  src/router.js
Labels: feature, UI

#115 feat: #113 행사 기본 정보 페이지 생성
  package-lock.json
  package.json
  src/pages/DashboardPage/DashboardInfo.jsx
  src/pages/DashboardPage/DashboardInfo.style.jsx
  src/pages/DashboardPage/index.js
  src/pages/index.js
  src/router.js
Labels: feature, UI

#116 feat: #113 이메일 예약 발송 페이지 구현
  src/pages/DashboardPage/DashboardEmail.jsx
  src/pages/DashboardPage/DashboardEmail.style.jsx
  src/pages/DashboardPage/DashboardInfo.jsx
  src/pages/DashboardPage/DashboardInfo.style.jsx
  src/pages/DashboardPage/index.js
  src/pages/index.js
  src/router.js
Labels: 💫 feature, 🎨 UI

#117 feat: #113 참석자 관리 페이지 구현
  src/pages/DashboardPage/DashboardAttendee.jsx
  src/pages/DashboardPage/DashboardAttendee.style.jsx
  src/pages/DashboardPage/index.js
  src/pages/index.js
  src/router.js
Labels: 💫 feature, 🎨 UI

#118 docs: #6 스크린샷 항목 추가
  .github/pull_request_template.md
Labels: 📃 docs

#119 feat: #107 사이드바 구현
  src/Layout/Layout.jsx
  src/components/Navigator/Navigator.jsx
  src/components/Navigator/Navigator.style.jsx
  src/components/Navigator/Sidebar.jsx
  src/components/Navigator/Sidebar.style.jsx
  src/components/Navigator/index.js
  src/components/index.js
  src/pages/DashboardPage/DashboardAttendee.style.jsx
  src/pages/DashboardPage/DashboardEmail.style.jsx
  src/pages/DashboardPage/DashboardInfo.style.jsx
  src/pages/DashboardPage/DashboardPage.jsx
  src/pages/DashboardPage/DashboardPage.style.jsx
  src/router.js
Labels: 💫 feature, 🎨 UI

#121 Feat:recoil-persist 추가
  package.json
  src/recoil/atoms/state.js
Labels: 📬 API

#122 modify: #107 페이지 하단 및 기타 여백 조정
  src/Layout/Layout.jsx
  src/Layout/PageLayout.jsx
  src/components/Navigator/Navigator.style.jsx
  src/components/Navigator/Sidebar.style.jsx
  src/pages/DashboardPage/DashboardAttendee.jsx
  src/pages/DashboardPage/DashboardAttendee.style.jsx
  src/pages/DashboardPage/DashboardEmail.jsx
  src/pages/DashboardPage/DashboardEmail.style.jsx
  src/pages/DashboardPage/DashboardInfo.jsx
  src/pages/DashboardPage/DashboardInfo.style.jsx
  src/pages/DashboardPage/DashboardPage.style.jsx
  src/pages/EventDetail/EventDetailPage.jsx
Labels: 🐞 bug fix

#123 dev to main
  .github/pull_request_template.md
  package-lock.json
  package.json
  public/index.html
  src/Layout/Layout.jsx
  src/Layout/PageLayout.jsx
  src/components/Background/BackgroundPage.jsx
  src/components/Calendar/DateCalendar.jsx
  src/components/Calendar/DateCalendarStyle.js
  src/components/Calendar/TimeCalendar.jsx
  src/components/Calendar/TimeCalendarStyle.js
  src/components/Navigator/Navigator.jsx
  src/components/Navigator/Navigator.style.jsx
  src/components/Navigator/Sidebar.jsx
  src/components/Navigator/Sidebar.style.jsx
  src/components/Navigator/index.js
  src/components/index.js
  src/components/navigator.jsx
  src/constants/tempData.js
  src/icons/registerPage/dot.svg
  src/pages/DashboardPage/DashboardAttendee.jsx
  src/pages/DashboardPage/DashboardAttendee.style.jsx
  src/pages/DashboardPage/DashboardEmail.jsx
  src/pages/DashboardPage/DashboardEmail.style.jsx
  src/pages/DashboardPage/DashboardInfo.jsx
  src/pages/DashboardPage/DashboardInfo.style.jsx
  src/pages/DashboardPage/DashboardPage.jsx
  src/pages/DashboardPage/DashboardPage.style.jsx
  src/pages/DashboardPage/index.js
  src/pages/EventDetail/AttendanceList.jsx
  src/pages/EventDetail/EventDetailPage.jsx
  src/pages/EventDetail/EventDetailPage.style.jsx
  src/pages/EventDetail/eventDetail.jsx
  src/pages/EventDetail/index.js
  src/pages/EventList/EventList.jsx
  src/pages/EventList/finishEvent.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/HomeCarousel/HomeCarousel.js
  src/pages/Home/HomeCarousel/HomeCarousel.jsx
  src/pages/Home/HomeStyle.js
  src/pages/index.js
  src/pages/registerPage/register.jsx
  src/recoil/atoms/state.js
  src/router.js
  src/styles/mediaQueries.style.js
Labels: 🌏 deploy

#124 modify: #87 테스트를 위한 반응현 구현 및 홈 화면 일부 수정
  package-lock.json
  src/components/AttendanceHeader/AttendanceHeader.jsx
  src/components/Navigator/Navigator.style.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/HomeStyle.js
Labels: 🎨 UI

#127 feat: #126 [공통] 컴포넌트 생성 및 전역 스타일 적용
  src/components/Button/BlueButton90.jsx
  src/components/Button/GrayButton90.jsx
  src/components/Button/TabButton90.jsx
  src/components/Button/index.js
  src/components/index.js
  src/pages/DashboardPage/DashboardAttendee.jsx
  src/pages/DashboardPage/DashboardAttendee.style.jsx
  src/pages/DashboardPage/DashboardEmail.jsx
  src/pages/DashboardPage/DashboardEmail.style.jsx
  src/pages/DashboardPage/DashboardInfo.jsx
  src/pages/DashboardPage/DashboardPage.jsx
  src/pages/DashboardPage/DashboardPage.style.jsx
  src/styles/CheckMateStyles.style.jsx
Labels: 🎨 UI

#131 hotfix: #130 사용자 테스트를 위한 상수값 수정 및 최신순으로 행사 목록 정렬
  src/constants/tempData.js
  src/pages/EventList/EventList.jsx
Labels: 🌏 deploy

#132 merge: hotfix/event-id to main
  src/constants/tempData.js
  src/pages/EventDetail/AttendanceList.jsx
  src/pages/EventDetail/EventDetailPage.jsx
  src/pages/EventDetail/EventDetailPage.style.jsx
Labels: 🌏 deploy

#134 docs: #133 README.md 수정
  README.md
Labels: 📃 docs

#135 feat: #113 참석자 관리 페이지 내 기능 구현
  src/pages/DashboardPage/DashboardAttendee.jsx
  src/pages/DashboardPage/DashboardAttendee.style.jsx
  src/pages/DashboardPage/SessionDateTab.jsx
Labels: 💫 feature

#138 feat: #113 이메일 전송 페이지 내 탭메뉴 API 연동 및 view 일부 수정
  package-lock.json
  package.json
  src/pages/AttendancePage/AttendanceSignPage.jsx
  src/pages/AttendancePage/AttendanceSignPage.style.jsx
  src/pages/AttendancePage/AttendanceStudentIdPage.jsx
  src/pages/AttendancePage/AttendanceStudentIdPage.style.jsx
  src/pages/AttendancePage/index.js
  src/pages/AttendanceSignPage/index.js
  src/pages/AttendanceStudentIdPage/index.js
  src/pages/DashboardPage/DashboardAttendeePage.jsx
  src/pages/DashboardPage/DashboardEmail.jsx
  src/pages/DashboardPage/DashboardEmailPage.jsx
  src/pages/DashboardPage/DashboardEmailPage.style.jsx
  src/pages/DashboardPage/DashboardInfoPage.jsx
  src/pages/DashboardPage/DashboardInfoPage.style.jsx
  src/pages/DashboardPage/index.js
  src/pages/index.js
  src/router.js
Labels: 💫 feature, 🎨 UI, 📬 API

#139 design: 출석 체크 버튼이 올라가는 부분 및 컬러 등 디테일 수정
  src/pages/EventList/EventList.jsx
  src/pages/EventList/EventListStyle.js
Labels: 🎨 UI

#140 #113 feat: 대시보드 페이지 API 연동
  src/components/Button/GrayButton90.jsx
  src/pages/DashboardPage/DashboardPage.jsx
  src/pages/DashboardPage/DashboardPage.style.jsx
Labels: 📬 API

#141 #113 feat: 참석자 관리 페이지 내 이름 오름차순으로 기본 설정
  src/pages/DashboardPage/DashboardAttendeePage.jsx
  src/pages/DashboardPage/DashboardAttendeePage.style.jsx
Labels: 🎨 UI

#143 #142 feat: 최신 행사가 앞에 오도록 수정
  src/pages/EventList/EventCard.jsx
  src/pages/EventList/EventCard.style.jsx
  src/pages/EventList/EventList.jsx
  src/pages/EventList/EventList.style.jsx
  src/pages/EventList/index.js
Labels: 💫 feature, 🎨 UI

#145 #144 feat: 상단 메뉴에 행사 제목 띄우는 api 연동
  src/components/Navigator/Navigator.jsx
  src/components/Navigator/Navigator.style.jsx
Labels: 🎨 UI, 📬 API

#146 #113 feat: 행사 상태에 따른 뱃지 색상 및 내용 변동
  src/pages/DashboardPage/DashboardPage.jsx
  src/pages/DashboardPage/DashboardPage.style.jsx
Labels: 🎨 UI

#148 #62 fix: 없는 학번일 경우 alert창 띄우기
  src/components/Navigator/Navigator.style.jsx
  src/pages/AttendancePage/AttendanceStudentIdPage.jsx
  src/pages/AttendancePage/AttendanceStudentIdPage.style.jsx
  src/pages/DashboardPage/DashboardPage.jsx
  src/pages/DashboardPage/DashboardPage.style.jsx
Labels: 🎨 UI

#149 #137 fix: 서명 페이지 헤더에 행사 타이틀 가져오는 API 수정
  src/pages/AttendancePage/AttendanceSignPage.jsx
  src/pages/AttendancePage/AttendanceSignPage.style.jsx
Labels: 🐞 bug fix, 📬 API

#150 #144 feat: 모바일 반응형시 햄버거 메뉴가 생성되는 기능 구현
  src/components/Navigator/Navigator.jsx
  src/components/Navigator/Navigator.style.jsx
  src/components/Navigator/Sidebar.style.jsx
  src/pages/DashboardPage/DashboardAttendeePage.jsx
  src/pages/DashboardPage/DashboardAttendeePage.style.jsx
  src/pages/DashboardPage/DashboardEmailPage.style.jsx
  src/pages/DashboardPage/DashboardInfoPage.style.jsx
  src/pages/DashboardPage/DashboardPage.style.jsx
Labels: 🎨 UI

#151 feat: 뒤로가기 버튼 추가
  src/pages/RegisterPage/RegisterComponents/BackButton.jsx
  src/pages/RegisterPage/RegisterComponents/DragnDrop.jsx
  src/pages/RegisterPage/RegisterComponents/RegisterFirst.jsx
  src/pages/RegisterPage/RegisterComponents/RegisterSecond.jsx
  src/pages/RegisterPage/RegisterComponents/RegisterSideBar.jsx
  src/pages/RegisterPage/RegisterComponents/RegisterSideBarStyle.js
  src/pages/RegisterPage/RegisterComponents/RegisterThird.jsx
  src/pages/RegisterPage/RegisterPage.jsx
  src/pages/RegisterPage/RegisterStyle.js
  src/recoil/atoms/state.js
  src/recoil/atoms/useResetAllState.js
Labels: 💫 feature, 🎨 UI

#152 #113 feat: 참석자 목록 페이지 내 전화 기능 구현
  src/pages/DashboardPage/DashboardAttendeePage.jsx
  src/pages/DashboardPage/DashboardAttendeePage.style.jsx
Labels: 💫 feature

#153 #113 feat: 행사 기본 정보에 데이터 불러오는 API 연동
  src/pages/DashboardPage/DashboardInfoPage.jsx
  src/pages/DashboardPage/DashboardInfoPage.style.jsx
  src/pages/DashboardPage/DashboardPage.style.jsx
Labels: 💫 feature, 🎨 UI, 📬 API

#154 #113 modify: 디테일 수정 및 담당자 연락처 유효성 검사
  src/components/Navigator/Sidebar.jsx
  src/pages/DashboardPage/DashboardPage.jsx
  src/pages/DashboardPage/DashboardPage.style.jsx
Labels: 💫 feature

#155 feat: 담당자 이름 입력창 생성 및 API 연동
  src/pages/DashboardPage/DashboardPage.jsx
  src/pages/DashboardPage/DashboardPage.style.jsx
Labels: 📬 API

#157 #113 feat: 담당자 정보 불러오는 API 연동
  src/pages/DashboardPage/DashboardPage.jsx
  src/pages/DashboardPage/DashboardPage.style.jsx
Labels: 💫 feature, 📬 API

#158 #113 feat: 참석자 명단 다운로드 받는 코드 추가
  src/pages/DashboardPage/DashboardAttendeePage.jsx
Labels: 📬 API

#161 #160 fix: 반대로 되어있던 eventTarget 수정
  src/pages/DashboardPage/DashboardInfoPage.jsx
  src/pages/DashboardPage/DashboardInfoPage.style.jsx
Labels: 🔧 fix

#162 modify: state명 변경
  src/pages/RegisterPage/RegisterComponents/DragnDrop.jsx
  src/pages/RegisterPage/RegisterComponents/RegisterFirst.jsx
  src/pages/RegisterPage/RegisterComponents/RegisterSecond.jsx
  src/pages/RegisterPage/RegisterComponents/RegisterSideBar.jsx
  src/pages/RegisterPage/RegisterComponents/RegisterThird.jsx
  src/pages/RegisterPage/RegisterStyle.js
  src/recoil/atoms/state.js
  src/recoil/atoms/useResetAllState.js
Labels: 🔧 fix

#163 #159 modify: EVENT_DATE import문 삭제
  src/pages/AttendancePage/AttendanceStudentIdPage.jsx
Labels: 🔧 fix

#166 #164 fix: 배포 오류 해결
  package-lock.json
  src/constants/tempData.js
Labels: 🌏 deploy

#165 #164 merge: dev to main
  README.md
  package-lock.json
  package.json
  public/img/OFFLINE.png
  public/img/ONLINE.png
  src/components/Button/BlueButton90.jsx
  src/components/Button/GrayButton90.jsx
  src/components/Button/TabButton90.jsx
  src/components/Button/index.js
  src/components/Navigator/Navigator.jsx
  src/components/Navigator/Navigator.style.jsx
  src/components/Navigator/Sidebar.jsx
  src/components/Navigator/Sidebar.style.jsx
  src/components/index.js
  src/constants/tempData.js
  src/pages/AttendancePage/AttendanceSignPage.jsx
  src/pages/AttendancePage/AttendanceSignPage.style.jsx
  src/pages/AttendancePage/AttendanceStudentIdPage.jsx
  src/pages/AttendancePage/AttendanceStudentIdPage.style.jsx
  src/pages/AttendancePage/index.js
  src/pages/AttendanceSignPage/index.js
  src/pages/AttendanceStudentIdPage/index.js
  src/pages/DashboardPage/DashboardAttendee.jsx
  src/pages/DashboardPage/DashboardAttendeePage.jsx
  src/pages/DashboardPage/DashboardAttendeePage.style.jsx
  src/pages/DashboardPage/DashboardEmail.jsx
  src/pages/DashboardPage/DashboardEmail.style.jsx
  src/pages/DashboardPage/DashboardEmailPage.jsx
  src/pages/DashboardPage/DashboardEmailPage.style.jsx
  src/pages/DashboardPage/DashboardInfo.jsx
  src/pages/DashboardPage/DashboardInfoPage.jsx
  src/pages/DashboardPage/DashboardInfoPage.style.jsx
  src/pages/DashboardPage/DashboardPage.jsx
  src/pages/DashboardPage/DashboardPage.style.jsx
  src/pages/DashboardPage/index.js
  src/pages/EventList/EventCard.jsx
  src/pages/EventList/EventCard.style.jsx
  src/pages/EventList/EventList.jsx
  src/pages/EventList/EventList.style.jsx
  src/pages/EventList/index.js
  src/pages/RegisterPage/RegisterComponents/BackButton.jsx
  src/pages/RegisterPage/RegisterComponents/DragnDrop.jsx
  src/pages/RegisterPage/RegisterComponents/RegisterFirst.jsx
  src/pages/RegisterPage/RegisterComponents/RegisterSecond.jsx
  src/pages/RegisterPage/RegisterComponents/RegisterSideBar.jsx
  src/pages/RegisterPage/RegisterComponents/RegisterSideBarStyle.js
  src/pages/RegisterPage/RegisterComponents/RegisterThird.jsx
  src/pages/RegisterPage/RegisterPage.jsx
  src/pages/RegisterPage/RegisterStyle.js
  src/pages/index.js
  src/pages/registerPage/register.jsx
  src/recoil/atoms/state.js
  src/recoil/atoms/useResetAllState.js
  src/router.js
  src/styles/CheckMateStyles.style.jsx
Labels: 🌏 deploy

#167 #160 fix: 대시보드 및 기본 정보 페이지 내 eventType, eventTarget API 연동
  src/pages/DashboardPage/DashboardAttendeePage.jsx
  src/pages/DashboardPage/DashboardEmailPage.jsx
  src/pages/DashboardPage/DashboardInfoPage.jsx
  src/pages/DashboardPage/DashboardPage.jsx
  src/pages/DashboardPage/DashboardPage.style.jsx
Labels: 📬 API, 🔧 fix

#169 #168 fix: 참석여부 수정 API 연동
  src/pages/DashboardPage/DashboardAttendeePage.jsx
Labels: 📬 API

#170 merge: dev to main
  src/pages/DashboardPage/DashboardAttendeePage.jsx
  src/pages/DashboardPage/DashboardEmailPage.jsx
  src/pages/DashboardPage/DashboardInfoPage.jsx
  src/pages/DashboardPage/DashboardPage.jsx
  src/pages/DashboardPage/DashboardPage.style.jsx
Labels: 🌏 deploy

#171 #144 modify: 모바일 사이즈로 화면사이즈가 줄어들면, 왼쪽 sidebar 사라지도록 구현
  src/Layout/PageLayout.jsx
  src/components/Navigator/Navigator.jsx
  src/components/Navigator/Navigator.style.jsx
  src/components/Navigator/Sidebar.jsx
  src/components/Navigator/Sidebar.style.jsx
  src/pages/DashboardPage/DashboardPage.jsx
Labels: 💫 feature

#173 #172 feat: eventTarget이 외부인인 경우 휴대폰 번호 뒷 4자리로 출석체크
  src/components/Modal/Modal.jsx
  src/pages/AttendancePage/AttendanceSignPage.jsx
  src/pages/AttendancePage/AttendanceSignPage.style.jsx
  src/pages/AttendancePage/AttendanceStudentIdPage.jsx
Labels: 💫 feature, 📬 API, 🔧 fix

#174 #164 merge: dev to main
  src/Layout/PageLayout.jsx
  src/components/Modal/Modal.jsx
  src/components/Navigator/Navigator.jsx
  src/components/Navigator/Navigator.style.jsx
  src/components/Navigator/Sidebar.jsx
  src/components/Navigator/Sidebar.style.jsx
  src/pages/AttendancePage/AttendanceSignPage.jsx
  src/pages/AttendancePage/AttendanceSignPage.style.jsx
  src/pages/AttendancePage/AttendanceStudentIdPage.jsx
  src/pages/DashboardPage/DashboardPage.jsx
Labels: 🌏 deploy

#175 #164 fix: 서명페이지 내 서명칸 사이즈 확대
  src/pages/AttendancePage/AttendanceSignPage.style.jsx
Labels: 🎨 UI

#176 #164 merge: dev to main
  src/pages/AttendancePage/AttendanceSignPage.style.jsx
Labels: 🌏 deploy

#179 #164 fix: 출석체크 오류 해결
  src/components/Modal/Modal.jsx
  src/pages/AttendancePage/AttendanceSignPage.jsx
  src/pages/AttendancePage/AttendanceSignPage.style.jsx
  src/pages/AttendancePage/AttendanceStudentIdPage.jsx
  src/pages/EventList/EventCard.jsx
  src/pages/EventList/EventCard.style.jsx
Labels: 🔧 fix

#181 #164 fix: USER_ID 수정
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.style.jsx
  src/components/Navigator/Sidebar.jsx
  src/constants/tempData.js
  src/pages/DashboardPage/DashboardPage.style.jsx
Labels: 🔧 fix

#182 #164 merge: dev to main
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.style.jsx
  src/components/Navigator/Sidebar.jsx
  src/constants/tempData.js
  src/pages/DashboardPage/DashboardPage.style.jsx
Labels: 🌏 deploy

#184 #183 feat: 참석자 명단을 담당자 메일로 자동 발송하는 기능 구현
  src/constants/tempData.js
  src/pages/DashboardPage/DashboardAttendeePage.jsx
  src/pages/DashboardPage/DashboardAttendeePage.style.jsx
  src/pages/DashboardPage/DashboardPage.jsx
Labels: 💫 feature, 🎨 UI, 📬 API

#185 #164 merge: dev to main
  src/constants/tempData.js
  src/pages/DashboardPage/DashboardAttendeePage.jsx
  src/pages/DashboardPage/DashboardAttendeePage.style.jsx
  src/pages/DashboardPage/DashboardPage.jsx
Labels: 🌏 deploy

#188 #164 merge: dev to main
  src/pages/DashboardPage/DashboardPage.jsx
Labels: 🌏 deploy

#190 #189 modify: USER_ID를 테스트 버전으로 변경
  src/constants/tempData.js
Labels: ✅ test

#191 #189 merge: dev to main
  src/constants/tempData.js
Labels: 🌏 deploy
