Repository CheckMate-sookmyung/CheckMate-client, pull requests merged in 2024-09, with the labels that each got.

#225 #224 refactor: 대시보드 api 코드 개선
  package-lock.json
  package.json
  src/Layout/Layout.jsx
  src/Layout/PageLayout.jsx
  src/Layout/index.js
  src/apis/attendance.js
  src/apis/event.js
  src/apis/index.js
  src/components/Footer/Footer.jsx
  src/components/Footer/index.js
  src/components/Sidebar/Sidebar.jsx
  src/components/Table/AttendeeTable.jsx
  src/components/TopNavigation/TopNavigation.jsx
  src/components/TopNavigation/TopNavigation.style.jsx
  src/components/index.js
  src/index.jsx
  src/pages/DashboardPage/DashboardAttendeePage.jsx
  src/pages/DashboardPage/DashboardInfoPage.jsx
  src/pages/DashboardPage/DashboardInfoPage.style.jsx
  src/pages/DashboardPage/DashboardMessagePage.jsx
  src/pages/DashboardPage/DashboardMessagePage.style.jsx
  src/pages/DashboardPage/DashboardPage.jsx
  src/pages/DashboardPage/DashboardPage.style.jsx
  src/pages/DashboardPage/DashboardStatisticPage.jsx
  src/pages/DashboardPage/DashboardStatisticPage.style.jsx
  src/pages/DashboardPage/index.js
  src/pages/EventCardListPage/EventCardListPage.jsx
  src/pages/EventCardListPage/EventCardListPage.style.jsx
  src/pages/Home/Home.jsx
  src/pages/RegisterPage/PageComponents/RegisterCompleted.jsx
  src/pages/RegisterPage/RegisterPage.jsx
  src/pages/TotalStatisticsPage/TotalStatisticsPage.jsx
  src/pages/TotalStatisticsPage/TotalStatisticsPage.style.jsx
  src/pages/index.js
  src/router.js
Labels: ♻️ refactor

#226 #223 design: tab menu, button 컴포넌트 스타일 수정
  src/components/Button/Button.jsx
  src/components/Button/Button.style.jsx
  src/components/TabMenu/TabMenu.jsx
  src/components/TabMenu/TabMenu.style.jsx
  src/components/TabMenu/index.js
  src/components/index.js
  src/pages/DashboardPage/DashboardAttendeePage.jsx
  src/pages/DashboardPage/DashboardMessagePage.jsx
Labels: 🎨 UI

#228 #227 design: 출석체크 화면 디자인 수정
  public/img/background-attendance.svg
  src/components/AttendanceHeader/AttendanceHeader.jsx
  src/components/AttendanceHeader/AttendanceHeader.style.jsx
  src/pages/AttendancePage/AttendanceStudentIdPage.jsx
  src/pages/AttendancePage/AttendanceStudentIdPage.style.jsx
Labels: 🎨 UI

#230 #229 fix: 대시보드 내 버튼 위치 조정
  src/components/Button/Button.style.jsx
  src/pages/DashboardPage/DashboardPage.style.jsx
Labels: 🎨 UI

#232 #231 docs: pr template 및 READ.ME 수정
  .github/pull_request_template.md
  README.md
Labels: 📃 docs

#236 #233 feat: 외부인 행사의 경우 테이블에서 학번, 학년 정보 제외시키기
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
  src/components/Table/AttendeeTable.jsx
  src/pages/DashboardPage/DashboardAttendeePage.jsx
Labels: 💫 feature, 📃 docs

#237 #233 feat: 참석자 관리 페이지 내 검색 기능 구현
  src/pages/DashboardPage/DashboardAttendeePage.jsx
Labels: 💫 feature

#238 #227 design: 서명 페이지 디자인 수정
  src/pages/AttendancePage/AttendanceSignPage.jsx
  src/pages/AttendancePage/AttendanceSignPage.style.jsx
Labels: 🎨 UI

#239 #227 design: 본인 확인 모달 디자인 수정
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.style.jsx
Labels: 🎨 UI

#240 #227 design: 숫자 입력 칸 너비 늘리기
  src/pages/AttendancePage/AttendanceStudentIdPage.style.jsx
Labels: 🎨 UI

#241 #202 modify: 미사용 코드 삭제, 행사등록 반응형 구현, UI 변경
  src/components/Calendar/DateCalendar.jsx
  src/components/Calendar/DateCalendarStyle.js
  src/components/Calendar/TimeCalendar.jsx
  src/components/Calendar/TimeCalendarStyle.js
  src/components/EventTypeCard/EventTypeCard.jsx
  src/components/EventTypeCard/EventTypeCard.style.js
  src/components/Scheduler/Scheduler.jsx
  src/components/Scheduler/Scheduler.style.js
  src/pages/RegisterPage/PageComponents/RegisterFirst.jsx
  src/pages/RegisterPage/PageComponents/RegisterFirst.style.js
  src/pages/RegisterPage/PageComponents/RegisterSecond.jsx
  src/pages/RegisterPage/PageComponents/RegisterSecond.style.js
  src/pages/RegisterPage/RegisterComponents/BackButton.jsx
  src/pages/RegisterPage/RegisterComponents/RegisterSideBar.jsx
  src/pages/RegisterPage/RegisterComponents/RegisterSideBarStyle.js
  src/pages/RegisterPage/RegisterComponents/Stepper/Stepper.jsx
  src/pages/RegisterPage/RegisterComponents/Stepper/Stepper.style.js
  src/pages/RegisterPage/RegisterPage.jsx
  src/recoil/atoms/state.js
Labels: 🐞 bug fix, 🎨 UI, ♻️ refactor, 🔧 fix

#242 fix: #202 행사 등록용 템플릿 변수 오류 수정
  src/pages/RegisterPage/PageComponents/RegisterSecond.jsx
Labels: 🐞 bug fix

#243 #227 fix: 서명 라이브러리 수정 및 user id 수정
  src/components/AttendanceHeader/AttendanceHeader.jsx
  src/components/AttendanceHeader/AttendanceHeader.style.jsx
  src/constants/tempData.js
  src/pages/AttendancePage/AttendanceSignPage.style.jsx
  src/pages/AttendancePage/AttendanceStudentIdPage.style.jsx
Labels: 🔧 fix

#245 #227 modify: 카카오톡 > 이메일 발송
  src/components/Sidebar/Sidebar.jsx
  src/constants/tempData.js
  src/pages/DashboardPage/DashboardMessagePage.jsx
Labels: 🎨 UI

#246 #227 design: attendance modal
  public/img/character-black-check.svg
  public/img/character-green-check.svg
  src/components/AttendanceConfirmModal/AttendanceConfirmModal.jsx
  src/components/AttendanceConfirmModal/AttendanceConfirmModal.style.jsx
  src/pages/AttendancePage/AttendanceSignPage.jsx
  src/pages/Home/Home.jsx
Labels: 🎨 UI

#248 feat: 통계 페이지 컴포넌트 구현
  src/components/DaterangePicker/DaterangePicker.jsx
  src/components/DaterangePicker/DaterangePicker.style.js
  src/components/DaterangePicker/index.js
  src/components/GraphBox/GraphBox.jsx
  src/components/GraphBox/GraphBox.style.js
  src/components/GraphBox/index.js
  src/components/index.js
Labels: 💫 feature

#249 #227 design: dashboard page layout
  src/components/EventTypeCard/index.js
  src/components/index.js
  src/pages/DashboardPage/DashboardAttendeePage.style.jsx
  src/pages/DashboardPage/DashboardInfoPage.style.jsx
  src/pages/DashboardPage/DashboardMessagePage.style.jsx
  src/pages/DashboardPage/DashboardPage.style.jsx
  src/pages/RegisterPage/PageComponents/RegisterFirst.jsx
Labels: 🎨 UI

#251 feat: #235 행사 목록 검색 기능 구현
  src/components/Search/Search.jsx
  src/components/Search/Search.style.js
  src/components/Search/index.js
  src/components/index.js
  src/pages/EventCardListPage/EventCardListPage.jsx
Labels: 💫 feature

#252 #250 design: register page 내 사이드바 수정
  src/pages/RegisterPage/RegisterComponents/RegisterSideBar.jsx
  src/pages/RegisterPage/RegisterComponents/RegisterSideBarStyle.js
Labels: 🎨 UI

#253 #250 design: 행사 등록 페이지 내 일부 폰트 크기 조정 및 줄 간격 조정
  src/pages/RegisterPage/RegisterComponents/RegisterSideBarStyle.js
Labels: 🎨 UI

#254 #250 design: 등록페이지 레이아웃 수정
  src/components/EventTypeCard/EventTypeCard.jsx
  src/components/EventTypeCard/EventTypeCard.style.js
  src/components/Input/Input.style.jsx
  src/components/Scheduler/Scheduler.jsx
  src/components/Scheduler/Scheduler.style.js
  src/components/Textarea/Textarea.style.jsx
  src/pages/RegisterPage/PageComponents/RegisterFirst.jsx
  src/pages/RegisterPage/PageComponents/RegisterFirst.style.js
  src/pages/RegisterPage/PageComponents/RegisterPage.style.js
  src/pages/RegisterPage/PageComponents/RegisterSecond.jsx
  src/pages/RegisterPage/PageComponents/RegisterSecond.style.js
  src/pages/RegisterPage/RegisterComponents/Button/BlueButton.jsx
  src/pages/RegisterPage/RegisterComponents/UploadBox/UploadBox.jsx
  src/pages/RegisterPage/RegisterComponents/UploadBox/UploadBox.style.js
Labels: 🎨 UI

#255 #250 design: 등록 페이지 내 스타일 수정
  src/components/Button/SlimButton.jsx
  src/components/Button/SlimButton.style.jsx
  src/components/Button/index.js
  src/components/EventTargetOption/EventTargetOption.jsx
  src/components/EventTargetOption/EventTargetOption.style.jsx
  src/components/Input/Input.style.jsx
  src/components/Scheduler/Scheduler.jsx
  src/components/Scheduler/Scheduler.style.js
  src/components/Textarea/Textarea.style.jsx
  src/pages/DashboardPage/DashboardAttendeePage.jsx
  src/pages/DashboardPage/DashboardAttendeePage.style.jsx
  src/pages/RegisterPage/PageComponents/RegisterFirst.jsx
  src/pages/RegisterPage/PageComponents/RegisterPage.style.js
  src/pages/RegisterPage/PageComponents/RegisterSecond.jsx
  src/pages/RegisterPage/RegisterComponents/RegisterSideBarStyle.js
  src/pages/RegisterPage/RegisterComponents/UploadBox/UploadBox.style.js
Labels: 🎨 UI

#257 #256 modify: search component props 수정 및 참석자 관리 페이지에 적용
  src/components/Search/Search.jsx
  src/pages/DashboardPage/DashboardAttendeePage.jsx
  src/pages/DashboardPage/DashboardAttendeePage.style.jsx
Labels: 🎨 UI

#260 #259 feat: 홈 화면 내 행사 수, 출석 완료 인원수 API 연동
  src/pages/Home/Home.Style.js
  src/pages/Home/Home.jsx
Labels: 📬 API

#262 feat: #98 구글 로그인을 위한 페이지 추가, API 연결
  src/components/TopNavigation/TopNavigation.jsx
  src/pages/LoadingPage/LoadingPage.jsx
  src/pages/LoadingPage/index.js
  src/pages/RegisterPage/index.js
  src/pages/index.js
  src/router.js
Labels: 💫 feature

#264 modify: #98 redirect_uri 수정
  src/components/TopNavigation/TopNavigation.jsx
Labels: 🔧 fix

#267 merge: dev to main
  src/pages/LoadingPage/LoadingPage.jsx
Labels: 🌏 deploy

#269 #268 design: 출석체크 페이지 내 다이얼 hover 효과 제거
  src/pages/AttendancePage/AttendanceStudentIdPage.style.jsx
Labels: 🎨 UI

#270 #234 feat: 세부 통계 페이지 임시 생성 후 더미데이터로 구현
  package-lock.json
  package.json
  src/components/TopNavigation/TopNavigation.jsx
  src/pages/DetailStatisticsPage/DetailStatisticsPage.jsx
  src/pages/DetailStatisticsPage/DetailStatisticsPage.style.jsx
  src/pages/DetailStatisticsPage/attendee.js
  src/pages/DetailStatisticsPage/index.js
  src/pages/index.js
  src/router.js
Labels: 💫 feature

#271 #234 modify: chart 디자인 일부 수정
  src/pages/DetailStatisticsPage/CompletionChart.jsx
  src/pages/DetailStatisticsPage/DetailStatisticsPage.jsx
  src/pages/DetailStatisticsPage/MajorChart.jsx
  src/pages/DetailStatisticsPage/YearChart.jsx
  src/pages/DetailStatisticsPage/attendee.js
Labels: 🎨 UI

#276 #275 modify: 더미데이터 구조 수정 및 이에 따른 코드 변경
  src/pages/DetailStatisticsPage/CompletionChart.jsx
  src/pages/DetailStatisticsPage/DetailStatisticsPage.jsx
  src/pages/DetailStatisticsPage/MajorChart.jsx
  src/pages/DetailStatisticsPage/YearChart.jsx
  src/pages/DetailStatisticsPage/attendee.js
Labels: 🔧 fix

#279 #278 [REFACTOR] 환경변수 env로 관리
  src/components/TopNavigation/TopNavigation.jsx
Labels: ♻️ refactor

#284 #283 move: 세부 행사 코드 이동 및 일부 폴더 구조 변경
  src/components/Sidebar/Sidebar.jsx
  src/components/TopNavigation/TopNavigation.jsx
  src/pages/AttendancePage/AttendanceSignPage/AttendanceSignPage.jsx
  src/pages/AttendancePage/AttendanceSignPage/AttendanceSignPage.style.jsx
  src/pages/AttendancePage/AttendanceStudentIdPage/AttendanceStudentIdPage.jsx
  src/pages/AttendancePage/AttendanceStudentIdPage/AttendanceStudentIdPage.style.jsx
  src/pages/AttendancePage/index.js
  src/pages/DashboardPage/DashboardAttendeePage/DashboardAttendeePage.jsx
  src/pages/DashboardPage/DashboardAttendeePage/DashboardAttendeePage.style.jsx
  src/pages/DashboardPage/DashboardEmailPage/DashboardEmailPage.jsx
  src/pages/DashboardPage/DashboardEmailPage/DashboardEmailPage.style.jsx
  src/pages/DashboardPage/DashboardInfoPage/DashboardInfoPage.jsx
  src/pages/DashboardPage/DashboardInfoPage/DashboardInfoPage.style.jsx
  src/pages/DashboardPage/DashboardStatisticPage.jsx
  src/pages/DashboardPage/DashboardStatisticPage.style.jsx
  src/pages/DashboardPage/DashboardStatisticPage/CompletionChart.jsx
  src/pages/DashboardPage/DashboardStatisticPage/DashboardStatisticPage.jsx
  src/pages/DashboardPage/DashboardStatisticPage/DashboardStatisticPage.style.jsx
  src/pages/DashboardPage/DashboardStatisticPage/MajorChart.jsx
  src/pages/DashboardPage/DashboardStatisticPage/YearChart.jsx
  src/pages/DashboardPage/DashboardStatisticPage/attendee.js
  src/pages/DashboardPage/index.js
  src/pages/DetailStatisticsPage/DetailStatisticsPage.jsx
  src/pages/DetailStatisticsPage/index.js
  src/pages/index.js
  src/router.js
Labels: ♻️ refactor

#286 #285 design: 행사 예정인 경우 글자 색상 red계열로 변경
  src/components/EventCard/EventCard.style.jsx
Labels: 🎨 UI

#288 #287 feat: 행사 목록 내 포스터 이미지가 null인 경우에 보여줄 대체 이미지 추가
  public/img/logo-background.svg
  public/img/logo-blue.svg
  public/img/logo-white.svg
  src/components/EventCard/EventCard.jsx
  src/components/Footer/Footer.jsx
  src/components/TopNavigation/TopNavigation.jsx
  src/pages/Home/Home.jsx
Labels: 💫 feature

#289 #235 feat: 전체, 진행중, 종료를 쿼리로 구현
  src/Pages/EventCardListPage/EventCardListPage.jsx
  src/components/Dropdown/Dropdown.style.jsx
  src/components/Sidebar/Sidebar.jsx
  src/components/TopNavigation/TopNavigation.jsx
  src/pages/EventCardListPage/EventCardListPage.jsx
  src/router.js
Labels: 💫 feature

#291 #290 remove: 불필요한 코드 삭제 및 변경
  src/components/Sidebar/Sidebar.jsx
  src/pages/DashboardPage/DashboardSurveyPage/DashboardSurveyPage.jsx
  src/pages/DashboardPage/DashboardSurveyPage/DashboardSurveyPage.style.jsx
  src/pages/DashboardPage/index.js
  src/pages/index.js
  src/router.js
Labels: 🎨 UI

#294 #247 feat: 그래프 차트 컴포넌트 구현
  src/components/GraphBox/GraphBox.jsx
  src/components/GraphBox/GraphBox.style.js
  src/pages/TotalStatisticsPage/GraphChart.jsx
  src/pages/TotalStatisticsPage/TableChart.jsx
  src/pages/TotalStatisticsPage/TotalStatisticsPage.jsx
  src/pages/TotalStatisticsPage/TotalStatisticsPage.style.jsx
Labels: 💫 feature

#295 #293 feat 행사 주소 입력칸 추가
  src/pages/RegisterPage/PageComponents/RegisterSecond.jsx
  src/pages/registerPage/PageComponents/RegisterSecond.jsx
Labels: 💫 feature

#298 #297 fix: 행사 기본 정보 오류 해결
  src/pages/DashboardPage/DashboardInfoPage/DashboardInfoPage.jsx
Labels: 🔧 fix

#301 #299 feat: 설문조사 링크 UI 구현
  src/pages/DashboardPage/DashboardSurveyPage/DashboardSurveyPage.jsx
  src/pages/DashboardPage/DashboardSurveyPage/DashboardSurveyPage.style.jsx
Labels: 🎨 UI

#302 #300 modify: email UI 수정
  src/components/Textarea/Textarea.jsx
  src/components/Textarea/Textarea.style.jsx
  src/pages/DashboardPage/DashboardEmailPage/DashboardEmailPage.jsx
  src/pages/DashboardPage/DashboardEmailPage/DashboardEmailPage.style.jsx
  src/pages/DashboardPage/DashboardSurveyPage/DashboardSurveyPage.jsx
  src/pages/DashboardPage/DashboardSurveyPage/DashboardSurveyPage.style.jsx
Labels: 🎨 UI

#304 #247 feat: 전체 통계 표 차트 구현
  src/components/DaterangePicker/DaterangePicker.style.js
  src/components/Table/Table.style.jsx
  src/components/Table/TotalStatisticsTable.jsx
  src/components/Table/index.js
  src/pages/TotalStatisticsPage/GraphChart.jsx
  src/pages/TotalStatisticsPage/TableChart.jsx
  src/pages/TotalStatisticsPage/TotalStatisticsPage.jsx
  src/pages/TotalStatisticsPage/TotalStatisticsPage.style.jsx
Labels: 💫 feature, 🎨 UI, 📬 API

#305 #303 feat: 유저 정보 없을 시 리디렉션
  src/components/TopNavigation/TopNavigation.jsx
  src/pages/LoadingPage/LoadingPage.jsx
  src/router.js
  src/services/index.js
  src/services/privateRoute/PrivateRoute.jsx
  src/services/privateRoute/index.js
Labels: 💫 feature, 📬 API

#306 #110 fix: 이동 주소 수정
  src/pages/Home/Home.jsx
Labels: 🔧 fix

#307 #292 modify: 라우터 event > events로 수정
  src/components/AttendanceHeader/AttendanceHeader.jsx
  src/components/EventCard/EventCard.jsx
  src/components/Sidebar/Sidebar.jsx
  src/components/TopNavigation/TopNavigation.jsx
  src/pages/DashboardPage/DashboardPage.jsx
  src/router.js
Labels: 🔧 fix

#310 #309 feat: 안내 메일 동의 칸 구현
  src/pages/RegisterPage/PageComponents/RegisterPage.style.js
  src/pages/RegisterPage/PageComponents/RegisterSecond.jsx
  src/pages/registerPage/PageComponents/RegisterSecond.jsx
Labels: 💫 feature

#314 #313 [FIX] API path 내 오타 수정
  src/apis/event.js
Labels: 🔧 fix

#316 #315 feat: `이메일 예약 발송`, `설문조사 링크 발송` 페이지 UI 수정 및 API 연동
  src/components/Button/Button.style.jsx
  src/pages/DashboardPage/DashboardEmailPage/DashboardEmailPage.jsx
  src/pages/DashboardPage/DashboardSurveyPage/DashboardSurveyPage.jsx
Labels: 💫 feature, 📬 API

#317 #292 fix: 참석자 관리 페이지 오류 수정 및 참석자 정보 가져오는 기능 구현
  src/pages/DashboardPage/DashboardAttendeePage/DashboardAttendeePage.jsx
Labels: 💫 feature

#319 #318 feat: 테이블에 출석시간 추가
  src/components/Table/AttendeeTable.jsx
  src/pages/DashboardPage/DashboardAttendeePage/AttendeeSearch.js
  src/pages/DashboardPage/DashboardAttendeePage/DashboardAttendeePage.jsx
Labels: 💫 feature

#322 #320 feat: 리디렉션 주소 변경
  src/services/privateRoute/PrivateRoute.jsx
Labels: 💫 feature

#323 #272 fix: 문제 있던 API path 수정
  src/Layout/PageLayout.jsx
  src/components/EventTypeCard/index.js
  src/components/EventTypeRadioGroup/EventTypeRadioGroup.jsx
  src/components/EventTypeRadioGroup/EventTypeRadioGroup.style.js
  src/components/EventTypeRadioGroup/index.js
  src/components/Sidebar/Sidebar.style.jsx
  src/components/Table/AttendeeTable.jsx
  src/components/UploadBox/UploadBox.jsx
  src/components/index.js
  src/pages/AttendancePage/AttendanceSignPage/AttendanceSignPage.jsx
  src/pages/AttendancePage/AttendanceStudentIdPage/AttendanceStudentIdPage.jsx
  src/pages/DashboardPage/DashboardAttendeePage/DashboardAttendeePage.style.jsx
  src/pages/DashboardPage/DashboardEmailPage/DashboardEmailPage.jsx
  src/pages/DashboardPage/DashboardEmailPage/DashboardEmailPage.style.jsx
  src/pages/DashboardPage/DashboardInfoPage/DashboardInfoPage.jsx
  src/pages/DashboardPage/DashboardInfoPage/DashboardInfoPage.style.jsx
  src/pages/DashboardPage/DashboardPage.jsx
  src/pages/DashboardPage/DashboardPage.style.jsx
  src/pages/DashboardPage/DashboardStatisticPage/DashboardStatisticPage.jsx
  src/pages/DashboardPage/DashboardStatisticPage/DashboardStatisticPage.style.jsx
  src/pages/DashboardPage/DashboardSurveyPage/DashboardSurveyPage.jsx
  src/pages/DashboardPage/DashboardSurveyPage/DashboardSurveyPage.style.jsx
  src/pages/RegisterPage/PageComponents/RegisterCompleted.jsx
  src/pages/RegisterPage/PageComponents/RegisterFirst.jsx
  src/pages/RegisterPage/PageComponents/RegisterPage.style.js
  src/pages/RegisterPage/RegisterComponents/Dropdown/CompletionDropdown.jsx
  src/services/attendanceService/attendanceService.js
Labels: 📬 API, 🔧 fix

#327 #326 fix: api 및 페이지 내용 일부 수정
  src/apis/attendance.js
  src/apis/event.js
  src/components/Dropdown/Dropdown.style.jsx
  src/components/Sidebar/Sidebar.jsx
  src/components/Table/AttendeeTable.jsx
  src/components/Table/Table.style.jsx
  src/pages/DashboardPage/DashboardAttendeePage/DashboardAttendeePage.jsx
  src/pages/DashboardPage/DashboardAttendeePage/DashboardAttendeePage.style.jsx
  src/pages/DashboardPage/DashboardEmailPage/DashboardEmailPage.jsx
  src/pages/DashboardPage/DashboardEmailPage/DashboardEmailPage.style.jsx
  src/pages/DashboardPage/DashboardInfoPage/DashboardInfoPage.jsx
  src/pages/DashboardPage/DashboardInfoPage/DashboardInfoPage.style.jsx
  src/pages/DashboardPage/DashboardPage.jsx
  src/pages/DashboardPage/DashboardPage.style.jsx
  src/pages/DashboardPage/DashboardStatisticPage/CompletionChart.jsx
  src/pages/DashboardPage/DashboardStatisticPage/DashboardStatisticPage.jsx
  src/pages/DashboardPage/DashboardStatisticPage/DashboardStatisticPage.style.jsx
  src/pages/DashboardPage/DashboardStatisticPage/MajorChart.jsx
  src/pages/DashboardPage/DashboardStatisticPage/YearChart.jsx
  src/pages/DashboardPage/DashboardSurveyPage/DashboardSurveyPage.jsx
  src/pages/DashboardPage/DashboardSurveyPage/DashboardSurveyPage.style.jsx
Labels: 💫 feature, 📬 API

#329 #328 feat: 유저 로그아웃/회원탈퇴 시를 위한 드랍다운 구현
  src/components/TopNavigation/TopNavigation.jsx
  src/components/UserDropdown/UserDropdown.jsx
  src/components/UserDropdown/UserDropdown.style.js
  src/components/UserDropdown/index.js
  src/components/index.js
Labels: 💫 feature

#330 #321 modify: API 스펙 변경 + 온라인 버전 시 최소 이수 기준 인풋 구현
  src/pages/RegisterPage/PageComponents/RegisterSecond.jsx
Labels: 📬 API, 🔧 fix

#336 merge: dev to main
  src/components/TopNavigation/TopNavigation.jsx
Labels: 🌏 deploy

#348 #347 feat: 메일로 명단 전송 API 연동 및 `즉시 다운로드`시 새 창에서 열리도록 수정
  src/pages/DashboardPage/DashboardAttendeePage/DashboardAttendeePage.jsx
Labels: 📬 API

#351 #350 design: 행사 카드 내 이미지와 버튼 사이 간격 조정
  src/components/EventCard/EventCard.style.jsx
Labels: 💫 feature

#353 #247 feat: 참석률 높은 행사 TOP 3 구현
  src/components/GraphBox/GraphBox.style.js
  src/pages/TotalStatisticsPage/EventsGraphChart.jsx
  src/pages/TotalStatisticsPage/EventsGraphChart.style.js
  src/pages/TotalStatisticsPage/GraphChart.jsx
  src/pages/TotalStatisticsPage/GraphChart.style.js
  src/pages/TotalStatisticsPage/TotalStatisticsPage.jsx
Labels: 💫 feature, 🎨 UI, 📬 API

#355 #354 fix: 엑셀 파일 업로드 시 오류 수정
  src/components/UploadBox/UploadBox.jsx
  src/pages/DashboardPage/DashboardInfoPage/DashboardInfoPage.jsx
Labels: 🐞 bug fix

#356 #352 fix: dashboard 내 api 수정 및 UI 추가
  src/components/AttendanceHeader/AttendanceHeader.jsx
  src/components/Table/TotalStatisticsTable.jsx
  src/pages/DashboardPage/DashboardEmailPage/DashboardEmailPage.jsx
  src/pages/DashboardPage/DashboardEmailPage/DashboardEmailPage.style.jsx
  src/pages/DashboardPage/DashboardPage.jsx
  src/pages/DashboardPage/DashboardPage.style.jsx
  src/pages/DashboardPage/DashboardSurveyPage/DashboardSurveyPage.jsx
  src/pages/DashboardPage/DashboardSurveyPage/DashboardSurveyPage.style.jsx
Labels: 🎨 UI, 📬 API

#359 #358 feat: 온라인 행사 시 행사 이수 기준 시간 추가
  src/pages/RegisterPage/PageComponents/RegisterSecond.jsx
Labels: 💫 feature

#360 #357 feat: 참석자 관리 페이지 내 모달창 생성 및 추가/삭제 UI 구현
  src/components/Modal/Modal.style.jsx
  src/components/Table/AttendeeTable.jsx
  src/components/Table/TotalStatisticsTable.jsx
  src/pages/DashboardPage/DashboardAttendeePage/DashboardAttendeePage.jsx
  src/pages/DashboardPage/DashboardAttendeePage/DashboardAttendeePage.style.jsx
Labels: 💫 feature, 🎨 UI

#361 #352 modify: 참석자 관리 페이지 내 모달창 일부 및 디테일 수정
  src/components/AttendanceHeader/AttendanceHeader.jsx
  src/components/TopNavigation/TopNavigation.style.jsx
  src/pages/DashboardPage/DashboardAttendeePage/DashboardAttendeePage.jsx
  src/pages/DashboardPage/DashboardAttendeePage/DashboardAttendeePage.style.jsx
  src/pages/DashboardPage/DashboardAttendeePage/UpdateAttendeeModal.js
  src/pages/DashboardPage/DashboardInfoPage/DashboardInfoPage.style.jsx
  src/pages/registerPage/PageComponents/RegisterSecond.jsx
Labels: 🎨 UI

#364 #362 feat: mail 기능구현
  src/apis/index.js
  src/apis/mail.js
  src/pages/DashboardPage/DashboardEmailPage/DashboardEmailPage.jsx
  src/pages/DashboardPage/DashboardSurveyPage/DashboardSurveyPage.jsx
Labels: 💫 feature, 📬 API

#365 merge: dev to main
  src/apis/index.js
  src/apis/mail.js
  src/components/AttendanceHeader/AttendanceHeader.jsx
  src/components/EventCard/EventCard.style.jsx
  src/components/GraphBox/GraphBox.style.js
  src/components/Modal/Modal.style.jsx
  src/components/Table/AttendeeTable.jsx
  src/components/Table/TotalStatisticsTable.jsx
  src/components/TopNavigation/TopNavigation.style.jsx
  src/components/UploadBox/UploadBox.jsx
  src/pages/DashboardPage/DashboardAttendeePage/DashboardAttendeePage.jsx
  src/pages/DashboardPage/DashboardAttendeePage/DashboardAttendeePage.style.jsx
  src/pages/DashboardPage/DashboardAttendeePage/UpdateAttendeeModal.js
  src/pages/DashboardPage/DashboardEmailPage/DashboardEmailPage.jsx
  src/pages/DashboardPage/DashboardEmailPage/DashboardEmailPage.style.jsx
  src/pages/DashboardPage/DashboardInfoPage/DashboardInfoPage.jsx
  src/pages/DashboardPage/DashboardInfoPage/DashboardInfoPage.style.jsx
  src/pages/DashboardPage/DashboardPage.jsx
  src/pages/DashboardPage/DashboardPage.style.jsx
  src/pages/DashboardPage/DashboardSurveyPage/DashboardSurveyPage.jsx
  src/pages/DashboardPage/DashboardSurveyPage/DashboardSurveyPage.style.jsx
  src/pages/Home/Home.Style.js
  src/pages/LoadingPage/LoadingPage.jsx
  src/pages/RegisterPage/PageComponents/RegisterSecond.jsx
  src/pages/TotalStatisticsPage/EventsGraphChart.jsx
  src/pages/TotalStatisticsPage/EventsGraphChart.style.js
  src/pages/TotalStatisticsPage/GraphChart.jsx
  src/pages/TotalStatisticsPage/GraphChart.style.js
  src/pages/TotalStatisticsPage/TotalStatisticsPage.jsx
  src/pages/registerPage/PageComponents/RegisterSecond.jsx
Labels: 🌏 deploy

#366 #352 fix: 메일 기능 및 참석자 추가/삭제 기능
  src/apis/attendance.js
  src/apis/mail.js
  src/components/Table/AttendeeTable.jsx
  src/pages/DashboardPage/DashboardAttendeePage/DashboardAttendeePage.jsx
  src/pages/DashboardPage/DashboardAttendeePage/UpdateAttendeeModal.js
  src/pages/DashboardPage/DashboardEmailPage/DashboardEmailPage.jsx
  src/pages/DashboardPage/DashboardSurveyPage/DashboardSurveyPage.jsx
Labels: 📬 API

#368 #367 feat: 행사 담당자 부분 임시 수정
  src/pages/DashboardPage/DashboardPage.jsx
Labels: 🎨 UI

#370 #363 feat: 줌 로그 분석 구현
  src/pages/DashboardPage/DashboardAttendeePage/DashboardAttendeePage.jsx
  src/pages/DashboardPage/DashboardAttendeePage/DashboardAttendeePage.style.jsx
  src/pages/DashboardPage/DashboardAttendeePage/LogAnalyzeButton.jsx
Labels: 💫 feature, 📬 API

#372 #371 fix: 템플릿 다운로드 에러 수정
  src/pages/RegisterPage/PageComponents/RegisterSecond.jsx
  src/pages/registerPage/PageComponents/RegisterSecond.jsx
Labels: 🐞 bug fix

#374 #369 fix: 출석체크시 휴대폰 번호 뒷자리가 중복될 경우 띄워줄 모달창 구현
  src/pages/AttendancePage/AttendanceStudentIdPage/AttendanceStudentIdPage.jsx
  src/pages/AttendancePage/AttendanceStudentIdPage/AttendanceStudentIdPage.style.jsx
Labels: 💫 feature
