Repository CheckMate-sookmyung/CheckMate-client, pull requests merged in 2024-05, with the labels that each got.

#13 Feat: step과 stepper 구현
  .eslintrc.js
  package-lock.json
  package.json
  src/App.test.js
  src/components/Step/Step.jsx
  src/components/Step/Step.style.jsx
  src/components/Step/index.js
  src/components/Stepper/Stepper.jsx
  src/components/Stepper/Stepper.style.jsx
  src/components/Stepper/index.js
  src/components/index.js
  src/icons/CheckIcon/CheckIcon.jsx
  src/icons/CheckIcon/index.js
  src/icons/index.js
  src/index.js
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/CheckMateStyles.style.jsx
  src/styles/GlobalStyle.style.jsx
  src/styles/PretendardFont.style.jsx
  src/styles/ResetStyles.style.jsx
  src/styles/index.js
Labels: feature, UI

#15 Feat: #3 서명 페이지 개발
  src/pages/SignPage/SignPage.jsx
  src/pages/SignPage/SignPage.style.jsx
  src/pages/SignPage/index.js
  src/pages/index.js
Labels: feature, UI

#16 Feat: #3 출석 페이지내 헤더 컴포넌트 개발
  src/components/AttendanceHeader/AttendanceHeader.jsx
  src/components/AttendanceHeader/AttendanceHeader.style.jsx
  src/components/AttendanceHeader/index.js
  src/components/Step/Step.style.jsx
  src/components/Stepper/Stepper.style.jsx
  src/components/index.js
  src/icons/CloseIcon/CloseIcon.jsx
  src/icons/CloseIcon/index.js
  src/icons/index.js
  src/pages/AttendancePage/AttendancePage.jsx
  src/pages/AttendancePage/AttendancePage.style.jsx
  src/pages/SignPage/SignPage.jsx
  src/pages/SignPage/SignPage.style.jsx
Labels: feature, UI

#18 Feat: #3 출석체크 화면에 헤더 컴포넌트 적용
  src/components/AttendanceHeader/AttendanceHeader.jsx
  src/pages/AttendancePage/AttendancePage.jsx
  src/pages/AttendancePage/AttendancePage.style.jsx
Labels: feature, UI

#19 Feat: router 설정 및 서명 페이지에 헤더 컴포넌트 적용
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/components/AttendanceHeader/AttendanceHeader.jsx
  src/components/AttendanceHeader/AttendanceHeader.style.jsx
  src/index.jsx
  src/pages/AttendancePage/index.js
  src/pages/AttendanceSignPage/AttendanceSignPage.jsx
  src/pages/AttendanceSignPage/AttendanceSignPage.style.jsx
  src/pages/AttendanceSignPage/index.js
  src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.jsx
  src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.style.jsx
  src/pages/AttendanceStudentIdPage/index.js
  src/pages/SignPage/SignPage.jsx
  src/pages/SignPage/index.js
  src/pages/index.js
  src/router.js
Labels: feature, UI

#21 feat: 행사 등록 페이지 뷰
  .eslintrc.js
  package-lock.json
  package.json
  src/App.js
  src/components/calendar/DateCalendar.jsx
  src/components/calendar/DateCalendarStyle.js
  src/components/calendar/TimeCalendar.jsx
  src/components/calendar/TimeCalendarStyle.js
  src/components/navigator.jsx
  src/pages/EventList/currentEvent.jsx
  src/pages/EventList/finishEvent.jsx
  src/pages/register.jsx
  src/pages/registerPage/register.jsx
  src/styles/CheckMateStyles.style.jsx
Labels: feature, UI

#23 Feat: 본인 확인 모달창 구현
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.style.jsx
  src/components/Modal/index.js
  src/components/index.js
  src/icons/CheckBoxIcon/CheckBoxIcon.jsx
  src/icons/CheckBoxIcon/index.js
  src/icons/CheckboxCheckedIcon/CheckboxCheckedIcon.jsx
  src/icons/CheckboxCheckedIcon/index.js
  src/icons/index.js
  src/pages/AttendanceSignPage/AttendanceSignPage.style.jsx
  src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.style.jsx
Labels: feature, UI

#25 Feat: #4 모달 창 개발 (이미 완료된 출석)
  package-lock.json
  src/components/AttendanceCompletedModal/AttendanceCompletedModal.jsx
  src/components/AttendanceCompletedModal/AttendanceCompletedModal.style.jsx
  src/components/AttendanceCompletedModal/index.js
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.style.jsx
  src/components/index.js
Labels: feature, UI

#35 Feat: #4 모달 창 개발 (출석 완료)
  src/components/AttendanceConfirmModal/AttendanceConfirmModal.jsx
  src/components/AttendanceConfirmModal/AttendanceConfirmModal.style.jsx
  src/components/AttendanceConfirmModal/index.js
  src/components/index.js
  src/icons/AttendanceConfirmIcon/AttendanceConfirmIcon.jsx
  src/icons/AttendanceConfirmIcon/index.js
  src/icons/index.js
Labels: feature, UI

#40 Feat: #3 전자 서명 기능 구현
  package-lock.json
  package.json
  src/pages/AttendanceSignPage/AttendanceSignPage.jsx
  src/pages/AttendanceSignPage/AttendanceSignPage.style.jsx
  src/pages/test.js
  src/pages/test2.js
Labels: feature, UI

#43 Feat: #41 본인 확인 모달창 구현
  public/index.html
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.style.jsx
  src/components/Portal/Portal.jsx
  src/index.jsx
  src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.jsx
Labels: feature, UI

#44 Style: #41 모달창 스타일링
  src/components/AttendanceCompletedModal/AttendanceCompletedModal.jsx
  src/components/AttendanceCompletedModal/AttendanceCompletedModal.style.jsx
  src/components/AttendanceCompletedModal/index.js
  src/components/AttendanceConfirmModal/AttendanceConfirmModal.jsx
  src/components/AttendanceConfirmModal/AttendanceConfirmModal.style.jsx
  src/components/Modal/Modal.style.jsx
  src/components/index.js
  src/pages/AttendanceSignPage/AttendanceSignPage.jsx
  src/pages/AttendanceSignPage/AttendanceSignPage.style.jsx
  src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.jsx
  src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.style.jsx
Labels: feature, UI

#59 Feat: #58 본인 확인 모달 디자인 수정
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.style.jsx
  src/constants/tempData.js
  src/icons/CheckBoxIcon/CheckBoxIcon.jsx
  src/icons/CheckBoxIcon/index.js
  src/icons/CheckboxCheckedIcon/CheckboxCheckedIcon.jsx
  src/icons/CheckboxCheckedIcon/index.js
  src/icons/index.js
  src/pages/AttendanceSignPage/AttendanceSignPage.jsx
  src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.style.jsx
Labels: feature

#61 design: api 일부 수정 및 모달 디자인 변경
  src/components/AttendanceConfirmModal/AttendanceConfirmModal.jsx
  src/components/AttendanceConfirmModal/AttendanceConfirmModal.style.jsx
  src/components/AttendanceHeader/AttendanceHeader.jsx
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.style.jsx
  src/pages/AttendanceSignPage/AttendanceSignPage.jsx
  src/pages/AttendanceSignPage/AttendanceSignPage.style.jsx
  src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.jsx
  src/services/attendanceService/attendanceService.js
Labels: UI, API

#66 fix: 행사 상세, 명단 수정
  src/components/Background/BackgroundPage.jsx
  src/components/navigator.jsx
  src/pages/EventDetail/AttendanceList.jsx
  src/pages/EventDetail/eventDetail.jsx
  src/pages/EventList/currentEvent.jsx
  src/router.js
Labels: UI, API, fix

#67 design: 헤더 컴포넌트 내 api 수정
  src/constants/tempData.js
  src/pages/AttendanceSignPage/AttendanceSignPage.jsx
  src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.jsx
Labels: API

#68 fix: 디자인 오류 수정
  src/components/Background/BackgroundPage.jsx
  src/pages/EventDetail/AttendanceList.jsx
  src/pages/registerPage/register.jsx
Labels: fix

#73 design: #72 출석체크 화면 내 다이얼 배치 수정
  src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.jsx
  src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.style.jsx
Labels: UI

#75 design: #72 출석체크 화면 디자인 재수정
  src/components/AttendanceHeader/AttendanceHeader.style.jsx
  src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.jsx
  src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.style.jsx
Labels: UI

#77 style: #72 폰트, 컬러, margin 등 디테일 수정
  src/pages/AttendanceSignPage/AttendanceSignPage.jsx
  src/pages/AttendanceSignPage/AttendanceSignPage.style.jsx
  src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.jsx
  src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.style.jsx
Labels: UI

#80 fix: 출석 API 연결
  src/pages/AttendanceSignPage/AttendanceSignPage.jsx
  src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.jsx
Labels: API, fix

#81 style: #72 ui-detail 수정
  src/components/AttendanceHeader/AttendanceHeader.style.jsx
  src/pages/AttendanceSignPage/AttendanceSignPage.style.jsx
  src/pages/AttendanceStudentIdPage/AttendanceStudentIdPage.style.jsx
  src/pages/EventDetail/AttendanceList.jsx
Labels: UI
